[package]
name = "touying-mmf-nsu"
version = "0.1.0"
entrypoint = "template.typ"
authors = ["Rustam Salimov <rustam2027@gmail.com>"]
license = "MIT"
description = "Mathematics & Mechanics faculty (NSU) themed Touying slides."
repository = "https://github.com/rustam2027/Touying-NSU-Template"
categories = ["presentation", "components"]
keywords = ["touying", "slides", "presentation", "academic", "Novosibirsk State University"]
exclude = ["example.pdf", "example.typ"]

[template]
path = "template"
entrypoint = "main.typ"
thumbnail = "thumbnail.png"
